FROM node:16-buster-slim
MAINTAINER 575065955@qq.com

RUN \
    sed -i 's/deb.debian.org/mirrors.cloud.tencent.com/g;s/security.debian.org/mirrors.cloud.tencent.com/g;s/security.debian.org/mirrors.cloud.tencent.com/g' /etc/apt/sources.list \
    && apt-get clean all && apt-get update && mkdir -p /usr/share/man/man1 \
    && apt-get install --no-install-recommends -y \
      wget xfonts-intl-chinese ttf-wqy-microhei  xfonts-wqy fonts-arphic-ukai fonts-cwtex-fs fonts-symbola xfonts-intl-european xfonts-intl-japanese \
      fontconfig libfreetype6 libjpeg62-turbo libpng16-16 libx11-6 libxcb1 libxext6 libxrender1 xfonts-75dpi \
      xfonts-base libfontconfig1 fontconfig-config libx11-data libxau6 libxdmcp6 ucf fonts-dejavu-core libexpat1 libbsd0 xfonts-utils libfontenc1 x11-common \
      xfonts-encodings sensible-utils default-jdk \
      wget --output-document=wkhtmltox.deb https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_amd64.deb \
    && (dpkg -i wkhtmltox.deb; echo ignore wkhtmlx error) && apt --fix-broken -y install && rm -rf wkhtmltox.deb \
    && npm config set registry https://registry.npm.taobao.org -g \
    && npm config set sass_binary_site http://cdn.npm.taobao.org/dist/node-sass -g \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /etc/rc.*/*dbus \
    && apt-get clean all

ENV PATH /usr/local/bin:$PATH
ENV NODE_ENV production
